config/routes.rb
Rails.application.routes.draw do
  root "links#index"
  get "/links", to: "links#all"
  get "/links/new", to: "links#new"
  post "/links", to: "links#create"
  delete 'links/:id', to: 'links#destroy'

  get "/:link_short", to: "links#access", as: "access_link"
  resources :links, only: [:edit, :update, :destory, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
    validates :link_source, presence: true
    validates :link_short, presence: true
  end

app/models/user.rb
class User < ApplicationRecord
    validates :full_name, presence: true
    validates :username, presence: true
    validates :password, confirmation: true, presence: true
    validates :password_confirmation, presence: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    before_action :set_link, only: [:edit, :update, :show, :destroy]
    def index
      
    end

    def show
      
    end

    def all
        @links = Link.all
        @base_url = "#{ENV["BASE_URL"]}"
    end

    def new
        @link = Link.new
    end
    

    def create
        @link = Link.new(link_param)
        if @link.save
          flash[:notice] = "New link successfully created"
          redirect_to links_path
        else
          render :new, status: :unprocessable_entity
        end
    end
    
    def update
        if @link.update(link_param)
          flash[:notice] = "Link was successfully updated"
          redirect_to links_path
        else
        #   flash[:error] = "Something went wrong"
          render 'edit', status: :unprocessable_entity
        end
    end

    def edit
    end

    def destroy
        @link.destroy
        redirect_to links_path, status: 303
    end

    def access
      link_param = params[:link_short]
      link = Link.where(link_short: link_param)
      # check if link is empty (if array is empty?)
      is_link_empty = link.empty?
    
      if is_link_empty
        puts "PLEASE MAKE THE LINK FIRST!!!!!!!!!"
        flash[:error] = "Link is not exist."
        redirect_to links_path, allow_other_host: true
      else
        # get source link
        get_source_link = link.pluck(:link_source)
        source_link = "#{get_source_link[0]}"
        redirect_to source_link, allow_other_host: true
      end
    end


    private

    def set_link
        @link = Link.find(params[:id])
    end

    def link_param
        params.require(:link).permit(:link_source, :link_short)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PendekIn</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with model: link do |form| %>
<div>
    <%= form.label :link_source %><br>
    <%= form.text_field :link_source %>
    <% link.errors.full_messages_for(:link_source).each do |message| %>
        <div><%= message %></div>
    <% end %>
</div>

<div>
    <%= form.label :link_short %><br>
    <%= form.text_field :link_short %>
    <% link.errors.full_messages_for(:link_short).each do |message| %>
        <div><%= message %></div>
    <% end %>
</div>


<div>
    <%= form.submit %>
</div>

<% end %>

app/views/links/all.html.erb
<h1>All Link</h1>

<table>
  <th>Source Link:</th>
  <th></th>
  <th>Shortened Link:</th>
    <% @links.each do |link| %>
      <tr>
        <td><a href=<%= "#{link.link_source}" %>><%= link.link_source %></a></td>
        <td></td>
        <td><%= link_to "#{link.link_short}", access_link_path(link.link_short) %></td>
        <td><%= link_to 'Edit', edit_link_path(link.id) %></td>  
        <td><%= link_to "Delete", [link], data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure to delete the generated link?"
        } %></td>  
        <td><small>Created <%= time_ago_in_words(link.created_at) %> ago, 
            edited <%= time_ago_in_words(link.updated_at) %> ago</small></td>
      </tr>
    <% end %>
</table>

<%= link_to "Create New Shortened Link", "links/new", method: :create %>

app/views/links/edit.html.erb
<h1>EDT LINK</h1>

<%= render 'form', link: @link %>

app/views/links/index.html.erb
<h1>Welcome to Pendek_in by Anggun Permata - 2022</h1>

<%= link_to "Create New", "links/new", method: :create %><br>
<%= link_to "See Shortened Links", links_path %>

app/views/links/new.html.erb
<h1>GENERATE NEW LINK</h1>

<%= render "form", link: @link %>

app/views/links/show.html.erb
<H1>DETAIL LINK</H1>
<p>Link (Source): <%= @link.link_source %></p>
<p>Link (Short): <%= @link.link_short %></p>